services:
  app:
    build: .
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: postgres:17.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose: 
      - 5432

volumes:
  postgres_data:
